config/routes.rb
Rails.application.routes.draw do
  resources :payments
  resources :payments

  root 'payments#index'
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  include Statesman::Adapters::ActiveRecordQueries

  has_many :payment_transitions

  scope :with_transaction, -> { includes(:payment_transitions) }

  attr_accessor :state

  before_update :change_state

  def state_machine
    @state_machine ||= PaymentStateMachine.new(self, transition_class: PaymentTransition)
  end

  private

  def self.transition_class
    PaymentTransition
  end

  def self.initial_state
    :pending
  end

  def change_state
    return unless state
    state_machine.transition_to!(self.state.to_sym)
  end
end

app/models/payment_transition.rb
class PaymentTransition < ActiveRecord::Base
  include Statesman::Adapters::ActiveRecordTransition

  belongs_to :payment, inverse_of: :payment_transitions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.with_transaction
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:name, :count, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stateman</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/payments/_form.html.slim
= form_for(@payment) do |f|
  - if @payment.errors.any?
    div#error_explanation
      h2
        = pluralize(@payment.errors.count, "error")
        | prohibited this payment from being saved:
      ul
        - @payment.errors.full_messages.each do |message|
          li = message

  div.field
    = f.label :name
    = f.text_field :name
  div.field
    = f.label :count
    = f.text_field :count
  div.field
    - @payment.state_machine.allowed_transitions.each do |state|
      = f.label :state
        strong> = state
        = f.radio_button :state, state
  div.actions
    = f.submit

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Payments</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Count</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.name %></td>
        <td><%= payment.count %></td>
        <td><%= payment.state_machine.current_state %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.slim
p#notice = notice
center
  p
    strong> Name:
    = @payment.name
  p
    strong> Count:
    = @payment.count
  p
    strong> Status:
    = @payment.state_machine.current_state

  = link_to 'Edit', edit_payment_path(@payment)
  |&nbsp;
  = link_to 'Back', payments_path